
export interface CityInfo {
  company: string;
  state: string;
}

const CITY_MAPPING: Record<string, CityInfo> = {
  "Maricá": { company: "CEG", state: "RJ" },
  "Rio Bonito": { company: "CGR", state: "RJ" },
  "Tanguá": { company: "CEG", state: "RJ" },
  "Itaboraí": { company: "CEG", state: "RJ" },
  "Guapimirim": { company: "CEG", state: "RJ" },
  "Magé": { company: "CEG", state: "RJ" },
  "Duque de Caxias": { company: "CEG", state: "RJ" },
  "Belford Roxo": { company: "CEG", state: "RJ" },
  "São João de Meriti": { company: "CEG", state: "RJ" },
  "Nilópolis": { company: "CEG", state: "RJ" },
  "Miguel Pereira": { company: "CGR", state: "RJ" },
  "Japeri": { company: "CEG", state: "RJ" },
  "Queimados": { company: "CEG", state: "RJ" },
  "Seropédica": { company: "CEG", state: "RJ" },
  "Paracambi": { company: "CEG", state: "RJ" },
  "Mangaratiba": { company: "CEG", state: "RJ" },
  "Piraí": { company: "CGR", state: "RJ" },
  "Barra do Piraí": { company: "CGR", state: "RJ" },
  "Pinheiral": { company: "CGR", state: "RJ" },
  "Volta Redonda": { company: "CGR", state: "RJ" },
  "Barra Mansa": { company: "CGR", state: "RJ" },
  "Porto Real": { company: "CEG", state: "RJ" },
  "Resende": { company: "CGR", state: "RJ" },
  "Casimiro de Abreu": { company: "CGR", state: "RJ" },
  "Arraial do Cabo": { company: "CGR", state: "RJ" },
  "Carapebus": { company: "CGR", state: "RJ" },
  "Rio das Ostras": { company: "CGR", state: "RJ" },
  "Cabo Frio": { company: "CGR", state: "RJ" },
  "Niterói": { company: "CEG", state: "RJ" },
  "São Gonçalo": { company: "CEG", state: "RJ" },
  "Itaguaí": { company: "CEG", state: "RJ" },
  "Porciúncula": { company: "CGR", state: "RJ" },
  "Varre-sai": { company: "CGR", state: "RJ" },
  "Natividade": { company: "CGR", state: "RJ" },
  "Bom Jesus do Itabapoana": { company: "CGR", state: "RJ" },
  "Laje do Muriaé": { company: "CGR", state: "RJ" },
  "Itaperuna": { company: "CGR", state: "RJ" },
  "Miracema": { company: "CGR", state: "RJ" },
  "São José de Ubá": { company: "CGR", state: "RJ" },
  "Aperibé": { company: "CGR", state: "RJ" },
  "Santo Antônio de Pádua": { company: "CGR", state: "RJ" },
  "Cambuci": { company: "CGR", state: "RJ" },
  "Itaocara": { company: "CGR", state: "RJ" },
  "Macuco": { company: "CGR", state: "RJ" },
  "Cordeiro": { company: "CGR", state: "RJ" },
  "Cantagalo": { company: "CGR", state: "RJ" },
  "Carmo": { company: "CGR", state: "RJ" },
  "Duas Barras": { company: "CGR", state: "RJ" },
  "Bom Jardim": { company: "CGR", state: "RJ" },
  "Sumidouro": { company: "CGR", state: "RJ" },
  "São José do Vale do Rio Preto": { company: "CGR", state: "RJ" },
  "Sapucaia": { company: "CGR", state: "RJ" },
  "Três Rios": { company: "CGR", state: "RJ" },
  "Areal": { company: "CGR", state: "RJ" },
  "Comendador Levy Gasparian": { company: "CGR", state: "RJ" },
  "Paty do Alferes": { company: "CGR", state: "RJ" },
  "Teresópolis": { company: "CGR", state: "RJ" },
  "Rio das Flores": { company: "CGR", state: "RJ" },
  "Italva": { company: "CGR", state: "RJ" },
  "São Sebastião do Alto": { company: "CGR", state: "RJ" },
  "Vassouras": { company: "CGR", state: "RJ" },
  "Mendes": { company: "CGR", state: "RJ" },
  "Engenheiro Paulo de Frontin": { company: "CGR", state: "RJ" },
  "Valença": { company: "CGR", state: "RJ" },
  "Rio Claro": { company: "CGR", state: "RJ" },
  "Araruama": { company: "CGR", state: "RJ" },
  "Iguaba Grande": { company: "CGR", state: "RJ" },
  "Armação de Búzios": { company: "CGR", state: "RJ" },
  "Nova Friburgo": { company: "CGR", state: "RJ" },
  "Cachoeiras de Macacu": { company: "CGR", state: "RJ" },
  "Itatiaia": { company: "CGR", state: "RJ" },
  "Quatis": { company: "CGR", state: "RJ" },
  "Cardoso Moreira": { company: "CGR", state: "RJ" },
  "São Fidélis": { company: "CGR", state: "RJ" },
  "Santa Maria Madalena": { company: "CGR", state: "RJ" },
  "Trajano de Morais": { company: "CGR", state: "RJ" },
  "Silva Jardim": { company: "CGR", state: "RJ" },
  "Saquarema": { company: "CGR", state: "RJ" },
  "Conceição de Macabú": { company: "CGR", state: "RJ" },
  "São Francisco de Itabapoana": { company: "CGR", state: "RJ" },
  "São Pedro da Aldeia": { company: "CGR", state: "RJ" },
  "São João da Barra": { company: "CGR", state: "RJ" },
  "Petrópolis": { company: "CGR", state: "RJ" },
  "Paraíba do Sul": { company: "CGR", state: "RJ" },
  "Parati": { company: "CGR", state: "RJ" },
  "Rio de Janeiro": { company: "CEG", state: "RJ" },
  "Angra dos Reis": { company: "CGR", state: "RJ" },
  "Mesquita": { company: "CEG", state: "RJ" },
  "Nova Iguaçu": { company: "CEG", state: "RJ" },
  "Campos dos Goytacazes": { company: "CGR", state: "RJ" },
  "Quisamá": { company: "CGR", state: "RJ" },
  "Macaé": { company: "CGR", state: "RJ" },
  "Sorocaba": { company: "SPS", state: "SP" },
  "Dobrada": { company: "SPS", state: "SP" },
  "Barra Bonita": { company: "SPS", state: "SP" },
  "Suzanápolis": { company: "SPS", state: "SP" },
  "Irapuã": { company: "SPS", state: "SP" },
  "Zacarias": { company: "SPS", state: "SP" },
  "Ilha Solteira": { company: "SPS", state: "SP" },
  "Cajati": { company: "SPS", state: "SP" },
  "Iporanga": { company: "SPS", state: "SP" },
  "Magda": { company: "SPS", state: "SP" },
  "Meridiano": { company: "SPS", state: "SP" },
  "Barra do Turvo": { company: "SPS", state: "SP" },
  "Ubirajara": { company: "SPS", state: "SP" },
  "Mirassolândia": { company: "SPS", state: "SP" },
  "Avaré": { company: "SPS", state: "SP" },
  "Promissão": { company: "SPS", state: "SP" },
  "Ubarana": { company: "SPS", state: "SP" },
  "Cedral": { company: "SPS", state: "SP" },
  "Santópolis do Aguapeí": { company: "SPS", state: "SP" },
  "Panorama": { company: "SPS", state: "SP" },
  "Guaiçara": { company: "SPS", state: "SP" },
  "Quatá": { company: "SPS", state: "SP" },
  "Tabapuã": { company: "SPS", state: "SP" },
  "Novo Horizonte": { company: "SPS", state: "SP" },
  "Lavínia": { company: "SPS", state: "SP" },
  "Bom Sucesso de Itararé": { company: "SPS", state: "SP" },
  "São João de Iracema": { company: "SPS", state: "SP" },
  "Parapuã": { company: "SPS", state: "SP" },
  "Indiana": { company: "SPS", state: "SP" },
  "Lençóis Paulista": { company: "SPS", state: "SP" },
  "Guararapes": { company: "SPS", state: "SP" },
  "Brejo Alegre": { company: "SPS", state: "SP" },
  "Pacaembu": { company: "SPS", state: "SP" },
  "Pongaí": { company: "SPS", state: "SP" },
  "Paraíso": { company: "SPS", state: "SP" },
  "Arealva": { company: "SPS", state: "SP" },
  "Taiaçu": { company: "SPS", state: "SP" },
  "Taquaral": { company: "SPS", state: "SP" },
  "Birigui": { company: "SPS", state: "SP" },
  "Caiuá": { company: "SPS", state: "SP" },
  "Lutécia": { company: "SPS", state: "SP" },
  "Paraguaçu Paulista": { company: "SPS", state: "SP" },
  "Álvares Machado": { company: "SPS", state: "SP" },
  "Sandovalina": { company: "SPS", state: "SP" },
  "Barão de Antonina": { company: "SPS", state: "SP" },
  "Itaju": { company: "SPS", state: "SP" },
  "Avanhandava": { company: "SPS", state: "SP" },
  "Ibate": { company: "SPS", state: "SP" },
  "Peruibe": { company: "SPS", state: "SP" },
  "Iguape": { company: "SPS", state: "SP" },
  "Morungaba": { company: "SPS", state: "SP" },
  "Santa Branca": { company: "SPS", state: "SP" },
  "Porto Ferreira": { company: "SPS", state: "SP" },
  "Rafard": { company: "SPS", state: "SP" },
  "Pradópolis": { company: "SPS", state: "SP" },
  "São Simão": { company: "SPS", state: "SP" },
  "Piedade": { company: "SPS", state: "SP" },
  "Pirassununga": { company: "SPS", state: "SP" },
  "Analândia": { company: "SPS", state: "SP" },
  "Iracemápolis": { company: "SPS", state: "SP" },
  "São José do Barreiro": { company: "SPS", state: "SP" },
  "Tambaú": { company: "SPS", state: "SP" },
  "Moji-mirim": { company: "SPS", state: "SP" },
  "Ferraz de Vasconcelos": { company: "SPS", state: "SP" },
  "Caieiras": { company: "SPS", state: "SP" },
  "São Sebastião da Grama": { company: "SPS", state: "SP" },
  "Quadra": { company: "SPS", state: "SP" },
  "Bragança Paulista": { company: "SPS", state: "SP" },
  "Piracaia": { company: "SPS", state: "SP" },
  "Itapecerica da Serra": { company: "SPS", state: "SP" },
  "Santo André": { company: "SPS", state: "SP" },
  "Tietê": { company: "SPS", state: "SP" },
  "Cordeirópolis": { company: "SPS", state: "SP" },
  "Vargem Grande Paulista": { company: "SPS", state: "SP" },
  "Cajuru": { company: "SPS", state: "SP" },
  "Pindamonhangaba": { company: "SPS", state: "SP" },
  "Severínia": { company: "SPS", state: "SP" },
  "Catiguá": { company: "SPS", state: "SP" },
  "Bocaina": { company: "SPS", state: "SP" },
  "Vista Alegre do Alto": { company: "SPS", state: "SP" },
  "Pindorama": { company: "SPS", state: "SP" },
  "Cafelândia": { company: "SPS", state: "SP" },
  "Potirendaba": { company: "SPS", state: "SP" },
  "Luiziânia": { company: "SPS", state: "SP" },
  "Sebastianópolis do Sul": { company: "SPS", state: "SP" },
  "Mirassol": { company: "SPS", state: "SP" },
  "José Bonifácio": { company: "SPS", state: "SP" },
  "Itaóca": { company: "SPS", state: "SP" },
  "Chavantes": { company: "SPS", state: "SP" },
  "Taquarituba": { company: "SPS", state: "SP" },
  "Manduri": { company: "SPS", state: "SP" },
  "União Paulista": { company: "SPS", state: "SP" },
  "Ribeirão do Sul": { company: "SPS", state: "SP" },
  "Barbosa": { company: "SPS", state: "SP" },
  "Taciba": { company: "SPS", state: "SP" },
  "Caiabu": { company: "SPS", state: "SP" },
  "Pracinha": { company: "SPS", state: "SP" },
  "Auriflama": { company: "SPS", state: "SP" },
  "Olímpia": { company: "SPS", state: "SP" },
  "Mirante do Paranapanema": { company: "SPS", state: "SP" },
  "Tarabai": { company: "SPS", state: "SP" },
  "Pirapozinho": { company: "SPS", state: "SP" },
  "Porangaba": { company: "SPS", state: "SP" },
  "Garça": { company: "SPS", state: "SP" },
  "Santo Anastácio": { company: "SPS", state: "SP" },
  "Álvaro de Carvalho": { company: "SPS", state: "SP" },
  "Regente Feijó": { company: "SPS", state: "SP" },
  "Uchoa": { company: "SPS", state: "SP" },
  "Monte Castelo": { company: "SPS", state: "SP" },
  "Andradina": { company: "SPS", state: "SP" },
  "Arujá": { company: "SPS", state: "SP" },
  "Registro": { company: "SPS", state: "SP" },
  "Rio Grande da Serra": { company: "SPS", state: "SP" },
  "Jambeiro": { company: "SPS", state: "SP" },
  "Cunha": { company: "SPS", state: "SP" },
  "Itapevi": { company: "SPS", state: "SP" },
  "Santo Antônio da Alegria": { company: "SPS", state: "SP" },
  "São Joaquim da Barra": { company: "SPS", state: "SP" },
  "Pereiras": { company: "SPS", state: "SP" },
  "Indaiatuba": { company: "SPS", state: "SP" },
  "Taubaté": { company: "SPS", state: "SP" },
  "Brodowski": { company: "SPS", state: "SP" },
  "Lorena": { company: "SPS", state: "SP" },
  "Nazaré Paulista": { company: "SPS", state: "SP" },
  "Pedra Bela": { company: "SPS", state: "SP" },
  "Conchal": { company: "SPS", state: "SP" },
  "Biritiba-mirim": { company: "SPS", state: "SP" },
  "Serrana": { company: "SPS", state: "SP" },
  "São José do Rio Pardo": { company: "SPS", state: "SP" },
  "Itanhaém": { company: "SPS", state: "SP" },
  "Corumbataí": { company: "SPS", state: "SP" },
  "Charqueada": { company: "SPS", state: "SP" },
  "Nuporanga": { company: "SPS", state: "SP" },
  "São José da Bela Vista": { company: "SPS", state: "SP" },
  "Serra Azul": { company: "SPS", state: "SP" },
  "Capela do Alto": { company: "SPS", state: "SP" },
  "Taboão da Serra": { company: "SPS", state: "SP" },
  "Luís Antônio": { company: "SPS", state: "SP" },
  "Américo Brasiliense": { company: "SPS", state: "SP" },
  "Dourado": { company: "SPS", state: "SP" },
  "Penápolis": { company: "SPS", state: "SP" },
  "Pontalinda": { company: "SPS", state: "SP" },
  "Pauliceia": { company: "SPS", state: "SP" },
  "Quintana": { company: "SPS", state: "SP" },
  "Eldorado": { company: "SPS", state: "SP" },
  "Nova Guataporanga": { company: "SPS", state: "SP" },
  "Braúna": { company: "SPS", state: "SP" },
  "Florínia": { company: "SPS", state: "SP" },
  "Urupês": { company: "SPS", state: "SP" },
  "Novais": { company: "SPS", state: "SP" },
  "Nipoã": { company: "SPS", state: "SP" },
  "Lupércio": { company: "SPS", state: "SP" },
  "Jaboticabal": { company: "SPS", state: "SP" },
  "Boracéia": { company: "SPS", state: "SP" },
  "Nantes": { company: "SPS", state: "SP" },
  "Arandu": { company: "SPS", state: "SP" },
  "Piacatu": { company: "SPS", state: "SP" },
  "Valparaíso": { company: "SPS", state: "SP" },
  "Guzolândia": { company: "SPS", state: "SP" },
  "Presidente Epitácio": { company: "SPS", state: "SP" },
  "Tupã": { company: "SPS", state: "SP" },
  "Alfredo Marcondes": { company: "SPS", state: "SP" },
  "Bofete": { company: "SPS", state: "SP" },
  "Iacri": { company: "SPS", state: "SP" },
  "João Ramalho": { company: "SPS", state: "SP" },
  "Presidente Bernardes": { company: "SPS", state: "SP" },
  "Guaraçaí": { company: "SPS", state: "SP" },
  "Irapuru": { company: "SPS", state: "SP" },
  "Batatais": { company: "SPS", state: "SP" },
  "Itatiba": { company: "SPS", state: "SP" },
  "Cajamar": { company: "SPS", state: "SP" },
  "Juquiá": { company: "SPS", state: "SP" },
  "Cananéia": { company: "SPS", state: "SP" },
  "Rincão": { company: "SPS", state: "SP" },
  "Pilar do Sul": { company: "SPS", state: "SP" },
  "Sarapuí": { company: "SPS", state: "SP" },
  "Sertãozinho": { company: "SPS", state: "SP" },
  "Brotas": { company: "SPS", state: "SP" },
  "Ilhabela": { company: "SPS", state: "SP" },
  "Águas de São Pedro": { company: "SPS", state: "SP" },
  "Arapeí": { company: "SPS", state: "SP" },
  "São Luís do Paraitinga": { company: "SPS", state: "SP" },
  "Jardinópolis": { company: "SPS", state: "SP" },
  "São João da Boa Vista": { company: "SPS", state: "SP" },
  "Serra Negra": { company: "SPS", state: "SP" },
  "Socorro": { company: "SPS", state: "SP" },
  "Francisco Morato": { company: "SPS", state: "SP" },
  "Leme": { company: "SPS", state: "SP" },
  "Santa Cruz da Esperança": { company: "SPS", state: "SP" },
  "Carapicuíba": { company: "SPS", state: "SP" },
  "Guarulhos": { company: "SPS", state: "SP" },
  "Patrocínio Paulista": { company: "SPS", state: "SP" },
  "Ribeirão Preto": { company: "SPS", state: "SP" },
  "Vargem Grande do Sul": { company: "SPS", state: "SP" },
  "São Caetano do Sul": { company: "SPS", state: "SP" },
  "São Carlos": { company: "SPS", state: "SP" },
  "Louveira": { company: "SPS", state: "SP" },
  "Sud Mennucci": { company: "SPS", state: "SP" },
  "Elisiário": { company: "SPS", state: "SP" },
  "Presidente Prudente": { company: "SPS", state: "SP" },
  "Terra Roxa": { company: "SPS", state: "SP" },
  "Fernando Prestes": { company: "SPS", state: "SP" },
  "Santa Mercedes": { company: "SPS", state: "SP" },
  "Jaci": { company: "SPS", state: "SP" },
  "Sabino": { company: "SPS", state: "SP" },
  "Boa Esperança do Sul": { company: "SPS", state: "SP" },
  "Bariri": { company: "SPS", state: "SP" },
  "Queiroz": { company: "SPS", state: "SP" },
  "Nova Europa": { company: "SPS", state: "SP" },
  "Tejupá": { company: "SPS", state: "SP" },
  "Inúbia Paulista": { company: "SPS", state: "SP" },
  "São Pedro do Turvo": { company: "SPS", state: "SP" },
  "Guapiaçu": { company: "SPS", state: "SP" },
  "Reginópolis": { company: "SPS", state: "SP" },
  "Poloni": { company: "SPS", state: "SP" },
  "Riversul": { company: "SPS", state: "SP" },
  "Itajobi": { company: "SPS", state: "SP" },
  "Itapeva": { company: "SPS", state: "SP" },
  "Barra do Chapéu": { company: "SPS", state: "SP" },
  "Taquarivaí": { company: "SPS", state: "SP" },
  "Pedrinhas Paulista": { company: "SPS", state: "SP" },
  "Fernão": { company: "SPS", state: "SP" },
  "Piraju": { company: "SPS", state: "SP" },
  "Itaberá": { company: "SPS", state: "SP" },
  "Nova Castilho": { company: "SPS", state: "SP" },
  "Ibirarema": { company: "SPS", state: "SP" },
  "Sagres": { company: "SPS", state: "SP" },
  "Martinópolis": { company: "SPS", state: "SP" },
  "Borebi": { company: "SPS", state: "SP" },
  "Lourdes": { company: "SPS", state: "SP" },
  "Glicério": { company: "SPS", state: "SP" },
  "Canitar": { company: "SPS", state: "SP" },
  "Santa Ernestina": { company: "SPS", state: "SP" },
  "Paranapanema": { company: "SPS", state: "SP" },
  "Teodoro Sampaio": { company: "SPS", state: "SP" },
  "Areiópolis": { company: "SPS", state: "SP" },
  "Pratânia": { company: "SPS", state: "SP" },
  "Palmeira D'oeste": { company: "SPS", state: "SP" },
  "Colina": { company: "SPS", state: "SP" },
  "Trabiju": { company: "SPS", state: "SP" },
  "Presidente Alves": { company: "SPS", state: "SP" },
  "Botucatu": { company: "SPS", state: "SP" },
  "Anhumas": { company: "SPS", state: "SP" },
  "Tupi Paulista": { company: "SPS", state: "SP" },
  "Ouro Verde": { company: "SPS", state: "SP" },
  "Onda Verde": { company: "SPS", state: "SP" },
  "Santo Antônio do Aracanguá": { company: "SPS", state: "SP" },
  "Jaborandi": { company: "SPS", state: "SP" },
  "Itaquaquecetuba": { company: "SPS", state: "SP" },
  "Sumaré": { company: "SPS", state: "SP" },
  "Ilha Comprida": { company: "SPS", state: "SP" },
  "Sete Barras": { company: "SPS", state: "SP" },
  "Campo Limpo Paulista": { company: "SPS", state: "SP" },
  "Amparo": { company: "SPS", state: "SP" },
  "São Bento do Sapucaí": { company: "SPS", state: "SP" },
  "Araçariguama": { company: "SPS", state: "SP" },
  "Mairinque": { company: "SPS", state: "SP" },
  "Aguaí": { company: "SPS", state: "SP" },
  "Dumont": { company: "SPS", state: "SP" },
  "Jaguariúna": { company: "SPS", state: "SP" },
  "Descalvado": { company: "SPS", state: "SP" },
  "Salto": { company: "SPS", state: "SP" },
  "Santa Rosa de Viterbo": { company: "SPS", state: "SP" },
  "Poá": { company: "SPS", state: "SP" },
  "Silveiras": { company: "SPS", state: "SP" },
  "Itapetininga": { company: "SPS", state: "SP" },
  "Tatuí": { company: "SPS", state: "SP" },
  "Joanópolis": { company: "SPS", state: "SP" },
  "Pinhalzinho": { company: "SPS", state: "SP" },
  "Tuiuti": { company: "SPS", state: "SP" },
  "Osasco": { company: "SPS", state: "SP" },
  "Mococa": { company: "SPS", state: "SP" },
  "Cotia": { company: "SPS", state: "SP" },
  "Piquete": { company: "SPS", state: "SP" },
  "Ipeúna": { company: "SPS", state: "SP" },
  "Santa Gertrudes": { company: "SPS", state: "SP" },
  "São Vicente": { company: "SPS", state: "SP" },
  "Tremembé": { company: "SPS", state: "SP" },
  "Guararema": { company: "SPS", state: "SP" },
  "Águas de Lindóia": { company: "SPS", state: "SP" },
  "São Bernardo do Campo": { company: "SPS", state: "SP" },
  "Franco da Rocha": { company: "SPS", state: "SP" },
  "Santa Bárbara D'oeste": { company: "SPS", state: "SP" },
  "Itupeva": { company: "SPS", state: "SP" },
  "Valinhos": { company: "SPS", state: "SP" },
  "Dois Córregos": { company: "SPS", state: "SP" },
  "Nova Alianca": { company: "SPS", state: "SP" },
  "Pitangueiras": { company: "SPS", state: "SP" },
  "Planalto": { company: "SPS", state: "SP" },
  "Narandiba": { company: "SPS", state: "SP" },
  "Ibitinga": { company: "SPS", state: "SP" },
  "Nova Campina": { company: "SPS", state: "SP" },
  "Apiaí": { company: "SPS", state: "SP" },
  "Cruzália": { company: "SPS", state: "SP" },
  "Guapiara": { company: "SPS", state: "SP" },
  "Tarumã": { company: "SPS", state: "SP" },
  "Júlio Mesquita": { company: "SPS", state: "SP" },
  "Rubiácea": { company: "SPS", state: "SP" },
  "Alto Alegre": { company: "SPS", state: "SP" },
  "Itararé": { company: "SPS", state: "SP" },
  "Cerqueira César": { company: "SPS", state: "SP" },
  "Guaimbê": { company: "SPS", state: "SP" },
  "Bilac": { company: "SPS", state: "SP" },
  "Nova Luzitânia": { company: "SPS", state: "SP" },
  "Buritama": { company: "SPS", state: "SP" },
  "Coroados": { company: "SPS", state: "SP" },
  "São José do Rio Preto": { company: "SPS", state: "SP" },
  "Taguaí": { company: "SPS", state: "SP" },
  "Flórida Paulista": { company: "SPS", state: "SP" },
  "Presidente Venceslau": { company: "SPS", state: "SP" },
  "Anhembi": { company: "SPS", state: "SP" },
  "Cajobi": { company: "SPS", state: "SP" },
  "Gália": { company: "SPS", state: "SP" },
  "Duartina": { company: "SPS", state: "SP" },
  "Cabrália Paulista": { company: "SPS", state: "SP" },
  "Paulistânia": { company: "SPS", state: "SP" },
  "Agudos": { company: "SPS", state: "SP" },
  "Platina": { company: "SPS", state: "SP" },
  "Ocauçu": { company: "SPS", state: "SP" },
  "Vera Cruz": { company: "SPS", state: "SP" },
  "Monções": { company: "SPS", state: "SP" },
  "Nova Independência": { company: "SPS", state: "SP" },
  "Ipiguá": { company: "SPS", state: "SP" },
  "Murutinga do Sul": { company: "SPS", state: "SP" },
  "Moji das Cruzes": { company: "SPS", state: "SP" },
  "Campinas": { company: "SPS", state: "SP" },
  "Jacupiranga": { company: "SPS", state: "SP" },
  "Pedro de Toledo": { company: "SPS", state: "SP" },
  "Juquitiba": { company: "SPS", state: "SP" },
  "Pariquera-açu": { company: "SPS", state: "SP" },
  "Varzea Paulista": { company: "SPS", state: "SP" },
  "Natividade da Serra": { company: "SPS", state: "SP" },
  "Itapira": { company: "SPS", state: "SP" },
  "Redenção da Serra": { company: "SPS", state: "SP" },
  "Monteiro Lobato": { company: "SPS", state: "SP" },
  "São Roque": { company: "SPS", state: "SP" },
  "Itirapuã": { company: "SPS", state: "SP" },
  "Franca": { company: "SPS", state: "SP" },
  "Limeira": { company: "SPS", state: "SP" },
  "Canas": { company: "SPS", state: "SP" },
  "Cachoeira Paulista": { company: "SPS", state: "SP" },
  "Cruzeiro": { company: "SPS", state: "SP" },
  "Divinolândia": { company: "SPS", state: "SP" },
  "Conchas": { company: "SPS", state: "SP" },
  "Monte Alegre do Sul": { company: "SPS", state: "SP" },
  "Jarinu": { company: "SPS", state: "SP" },
  "Atibaia": { company: "SPS", state: "SP" },
  "Mongaguá": { company: "SPS", state: "SP" },
  "Aparecida": { company: "SPS", state: "SP" },
  "Ubatuba": { company: "SPS", state: "SP" },
  "Diadema": { company: "SPS", state: "SP" },
  "Pedreira": { company: "SPS", state: "SP" },
  "Itariri": { company: "SPS", state: "SP" },
  "Jandira": { company: "SPS", state: "SP" },
  "Jacareí": { company: "SPS", state: "SP" },
  "São Lourenço da Serra": { company: "SPS", state: "SP" },
  "Cesário Lange": { company: "SPS", state: "SP" },
  "Embu": { company: "SPS", state: "SP" },
  "Praia Grande": { company: "SPS", state: "SP" },
  "Morro Agudo": { company: "SPS", state: "SP" },
  "Vinhedo": { company: "SPS", state: "SP" },
  "Santa Lúcia": { company: "SPS", state: "SP" },
  "Guará": { company: "SPS", state: "SP" },
  "Bebedouro": { company: "SPS", state: "SP" },
  "Valentim Gentil": { company: "SPS", state: "SP" },
  "Oriente": { company: "SPS", state: "SP" },
  "Santa Adelia": { company: "SPS", state: "SP" },
  "Votuporanga": { company: "SPS", state: "SP" },
  "Ribeirão Grande": { company: "SPS", state: "SP" },
  "Macaubal": { company: "SPS", state: "SP" },
  "Macatuba": { company: "SPS", state: "SP" },
  "Oscar Bressane": { company: "SPS", state: "SP" },
  "Sales": { company: "SPS", state: "SP" },
  "Pirajuí": { company: "SPS", state: "SP" },
  "Bady Bassitt": { company: "SPS", state: "SP" },
  "Clementina": { company: "SPS", state: "SP" },
  "Arco-íris": { company: "SPS", state: "SP" },
  "Nova Canaã Paulista": { company: "SPS", state: "SP" },
  "Águas de Santa Bárbara": { company: "SPS", state: "SP" },
  "Balbinos": { company: "SPS", state: "SP" },
  "Itapirapuã Paulista": { company: "SPS", state: "SP" },
  "Ibirá": { company: "SPS", state: "SP" },
  "Ipaussu": { company: "SPS", state: "SP" },
  "Fartura": { company: "SPS", state: "SP" },
  "Itapura": { company: "SPS", state: "SP" },
  "Itápolis": { company: "SPS", state: "SP" },
  "Nova Granada": { company: "SPS", state: "SP" },
  "Espírito Santo do Turvo": { company: "SPS", state: "SP" },
  "Lucélia": { company: "SPS", state: "SP" },
  "Bento de Abreu": { company: "SPS", state: "SP" },
  "Itaí": { company: "SPS", state: "SP" },
  "Osvaldo Cruz": { company: "SPS", state: "SP" },
  "Salmourão": { company: "SPS", state: "SP" },
  "Gabriel Monteiro": { company: "SPS", state: "SP" },
  "Rinópolis": { company: "SPS", state: "SP" },
  "Altair": { company: "SPS", state: "SP" },
  "Campina do Monte Alegre": { company: "SPS", state: "SP" },
  "Estrela do Norte": { company: "SPS", state: "SP" },
  "São Manuel": { company: "SPS", state: "SP" },
  "Santa Maria da Serra": { company: "SPS", state: "SP" },
  "Pardinho": { company: "SPS", state: "SP" },
  "Guarantã": { company: "SPS", state: "SP" },
  "Taiúva": { company: "SPS", state: "SP" },
  "Torrinha": { company: "SPS", state: "SP" },
  "Taquaritinga": { company: "SPS", state: "SP" },
  "Marília": { company: "SPS", state: "SP" },
  "Bauru": { company: "SPS", state: "SP" },
  "Piratininga": { company: "SPS", state: "SP" },
  "Pompéia": { company: "SPS", state: "SP" },
  "Ourinhos": { company: "SPS", state: "SP" },
  "Torre de Pedra": { company: "SPS", state: "SP" },
  "Echaporã": { company: "SPS", state: "SP" },
  "Bastos": { company: "SPS", state: "SP" },
  "Rancharia": { company: "SPS", state: "SP" },
  "Ribeirão dos Índios": { company: "SPS", state: "SP" },
  "Dracena": { company: "SPS", state: "SP" },
  "Gastão Vidigal": { company: "SPS", state: "SP" },
  "Junqueirópolis": { company: "SPS", state: "SP" },
  "Hortolândia": { company: "SPS", state: "SP" },
  "Tapiraí": { company: "SPS", state: "SP" },
  "Cosmópolis": { company: "SPS", state: "SP" },
  "Salesópolis": { company: "SPS", state: "SP" },
  "Monte Mor": { company: "SPS", state: "SP" },
  "Capivari": { company: "SPS", state: "SP" },
  "Lagoinha": { company: "SPS", state: "SP" },
  "Pontal": { company: "SPS", state: "SP" },
  "Santo Antônio do Pinhal": { company: "SPS", state: "SP" },
  "São Miguel Arcanjo": { company: "SPS", state: "SP" },
  "Saltinho": { company: "SPS", state: "SP" },
  "Laranjal Paulista": { company: "SPS", state: "SP" },
  "Cravinhos": { company: "SPS", state: "SP" },
  "Bananal": { company: "SPS", state: "SP" },
  "Guarujá": { company: "SPS", state: "SP" },
  "Santos": { company: "SPS", state: "SP" },
  "Queluz": { company: "SPS", state: "SP" },
  "Tapiratiba": { company: "SPS", state: "SP" },
  "Mogi-guaçu": { company: "SPS", state: "SP" },
  "São Paulo": { company: "SPS", state: "SP" },
  "Vargem": { company: "SPS", state: "SP" },
  "São José dos Campos": { company: "SPS", state: "SP" },
  "Igaratá": { company: "SPS", state: "SP" },
  "Araras": { company: "SPS", state: "SP" },
  "Areias": { company: "SPS", state: "SP" },
  "Potim": { company: "SPS", state: "SP" },
  "São Pedro": { company: "SPS", state: "SP" },
  "Cássia dos Coqueiros": { company: "SPS", state: "SP" },
  "Mairiporã": { company: "SPS", state: "SP" },
  "Estiva Gerbi": { company: "SPS", state: "SP" },
  "Bertioga": { company: "SPS", state: "SP" },
  "Restinga": { company: "SPS", state: "SP" },
  "Caçapava": { company: "SPS", state: "SP" },
  "Jumirim": { company: "SPS", state: "SP" },
  "Santana de Parnaiba": { company: "SPS", state: "SP" },
  "Cândido Rodrigues": { company: "SPS", state: "SP" },
  "Ariranha": { company: "SPS", state: "SP" },
  "Gavião Peixoto": { company: "SPS", state: "SP" },
  "General Salgado": { company: "SPS", state: "SP" },
  "Marinópolis": { company: "SPS", state: "SP" },
  "Matão": { company: "SPS", state: "SP" },
  "Ribeirão Bonito": { company: "SPS", state: "SP" },
  "Catanduva": { company: "SPS", state: "SP" },
  "Adolfo": { company: "SPS", state: "SP" },
  "Timburi": { company: "SPS", state: "SP" },
  "Óleo": { company: "SPS", state: "SP" },
  "São João das Duas Pontes": { company: "SPS", state: "SP" },
  "Cândido Mota": { company: "SPS", state: "SP" },
  "Itapuí": { company: "SPS", state: "SP" },
  "Lucianópolis": { company: "SPS", state: "SP" },
  "Guariba": { company: "SPS", state: "SP" },
  "Borá": { company: "SPS", state: "SP" },
  "Ribeirão Branco": { company: "SPS", state: "SP" },
  "Palmital": { company: "SPS", state: "SP" },
  "Bernardino de Campos": { company: "SPS", state: "SP" },
  "Iacanga": { company: "SPS", state: "SP" }
};

export function getCompanyByCity(cityName: string): CityInfo | null {
  if (!cityName) return null;
  
  // Normalize string for better matching (handling case and slight variations)
  const normalizedSearch = cityName.trim();
  
  // Direct match first
  if (CITY_MAPPING[normalizedSearch]) {
    return CITY_MAPPING[normalizedSearch];
  }
  
  // Case-insensitive fallback
  const foundKey = Object.keys(CITY_MAPPING).find(
    key => key.toLowerCase() === normalizedSearch.toLowerCase()
  );
  
  if (foundKey) {
    return CITY_MAPPING[foundKey];
  }
  
  return null;
}
