-- Create integrated_requests table with exact columns from requests.json
CREATE TABLE IF NOT EXISTS public.integrated_requests (
    "id" BIGINT PRIMARY KEY,
    "NRO_ESTUDO" TEXT,
    "FK_MODELO" TEXT DEFAULT '',
    "EMPRESA" TEXT,
    "DAT_EN_SEP" TEXT,
    "NRO_EST_AN" TEXT,
    "SOL_ORGAO" INTEGER,
    "SOL_RESPON" TEXT,
    "MEMORANDO" TEXT DEFAULT '',
    "MEMO_NUM" TEXT DEFAULT '',
    "MEMO_DATA" TEXT DEFAULT '',
    "TITULO" TEXT,
    "LOCALIZ" TEXT,
    "GRUPO_EST" INTEGER,
    "TIPO_EST" INTEGER,
    "DAT_IN_SEP" TEXT,
    "DAT_SA_SEP" TEXT,
    "PRESSAO" TEXT,
    "RESP_SEPLA" TEXT,
    "STATUS" INTEGER,
    "OBSERVS" TEXT,
    "OPERADOR_M" TEXT DEFAULT '',
    "DATA_M" TEXT DEFAULT '',
    "Bairro" TEXT,
    "Municipio" TEXT,
    "TPGASS" TEXT,
    "PRESGAS" TEXT,
    "NumEconomias" INTEGER,
    "VazaoSol" NUMERIC,
    "VazaoInsta" NUMERIC,
    "UnidSol" TEXT DEFAULT 'm³/h',
    "ConsMens" NUMERIC,
    "QDC" NUMERIC DEFAULT 0,
    "PresSolMax" NUMERIC,
    "PresSolMin" NUMERIC,
    "HorOpeIni" TEXT DEFAULT '',
    "HorOpeFin" TEXT DEFAULT '',
    "DiaOpeMes" INTEGER,
    "ObsEstudSol" TEXT DEFAULT '',
    "PresClieMax" TEXT,
    "PresClieMin" TEXT,
    "PresClieGarant" TEXT,
    "CODCARSEP" INTEGER DEFAULT 0,
    "PresSol" TEXT,
    "StatusEntrega" TEXT,
    "ObservaResp" TEXT,
    "RegulardoSN" BOOLEAN DEFAULT FALSE,
    "ReguladroVazao" TEXT DEFAULT '',
    "HoraFunciona" TEXT DEFAULT '',
    "CriadorRegistro" TEXT DEFAULT '',
    "DataCriaReg" TEXT DEFAULT '',
    "PressaoResposta" TEXT,
    "CustoRegulador" TEXT DEFAULT '0,00',
    "PressaoEntrada" NUMERIC,
    "unidPresEnt" TEXT,
    "PressaoSaida" NUMERIC,
    "unidPresSai" TEXT,
    "VazaoFutura" NUMERIC DEFAULT 0,
    "fd" NUMERIC,
    "fp" NUMERIC,
    "vu" NUMERIC,
    "Diversificar" NUMERIC,
    "dtEntregaPrevista" TEXT,
    "EmailContato" TEXT,
    "EntradaReal" TEXT,
    "carta_sepla" TEXT DEFAULT '',
    "EMAIL_ENVIADO" BOOLEAN DEFAULT FALSE,
    "DAT_PREN_INI_OP" TEXT DEFAULT '',
    "CROQUI" BOOLEAN DEFAULT FALSE,
    "PRESCALC" NUMERIC,
    "PRAZ_EST_CONST" NUMERIC DEFAULT 0,
    "CONSUMO_ESTIMADO" NUMERIC DEFAULT 0,
    "PRESSAO_INICIAL" NUMERIC DEFAULT 0,
    "PRESSAO_FINAL" NUMERIC DEFAULT 0,
    "PRESSAO_ABSOLUTA" NUMERIC DEFAULT 0,
    "PRESSAO_ATM" NUMERIC DEFAULT 0,
    "CODIGO_PASTA" INTEGER DEFAULT 0,
    "TIP_ES" INTEGER,
    "GRUPORED" INTEGER,
    "SIGEP" TEXT DEFAULT 'FALSO',
    "BAIXA_SIGEP" TEXT DEFAULT 'FALSO',
    "Preparacion" TEXT DEFAULT '',
    "Simulacao" TEXT DEFAULT '',
    "Supervision" TEXT DEFAULT '',
    "Tempo" TEXT DEFAULT '',
    "TempoEstimado" TEXT DEFAULT '',
    "RedeExtTotal" TEXT DEFAULT '',
    "OperadorConta" TEXT DEFAULT '',
    "IDSIGEP" TEXT,
    "IDSIGEPVINC" TEXT DEFAULT '',
    "NumEconomiasComIndEtc" INTEGER,
    "VazaoSolComIndEtc" NUMERIC,
    "UnidSolComIndEtc" TEXT DEFAULT 'm³/h',
    "ESTRERERIDO" TEXT DEFAULT '',
    "GrauDificult" INTEGER,
    "REGGNV" INTEGER DEFAULT 0,
    "EstudoRelevante" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS
ALTER TABLE public.integrated_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_select_integrated_requests" ON public.integrated_requests
FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated_insert_integrated_requests" ON public.integrated_requests
FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "authenticated_update_integrated_requests" ON public.integrated_requests
FOR UPDATE TO authenticated USING (true);

CREATE POLICY "authenticated_delete_integrated_requests" ON public.integrated_requests
FOR DELETE TO authenticated USING (true);
